### PR TITLE
fix(barman): Adjust slot-creation

### PR DESCRIPTION
**Pull request by ggggut**
# Description

Hello, creating a slot failed on our side because `ERROR: Unknown server 'pg'`.
I found it hardcoded in the cronjob. 
Wouldn't it be better to use the `postgres.host` value for creating the db slot?
Let me know what you think!

Best

# Issues

````bash
barman.server ERROR: Check 'replication slot' failed for server 'xxxxxxx'
	replication slot: FAILED (replication slot 'barman' doesn't exist. Please execute 'barman receive-wal --create-slot xxxxxxx')
	directories: OK
	retention policy settings: OK
````

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run`
* [ ] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by hairmare** [comment]
`postgres.host` does feel much better than having a hardcoded `pg` string. It should probably also get surfaced in `values.yaml`. 

For the `barman.backups` thing to work it would probably also need some `if hasKey`/`$.Values` stuff in the template (like what is already there for backupSchedule).

**Comment by ggggut** [comment]
thank you! i will look into it tomorrow

**Comment by ggggut** [comment]
The `barman.backups` key works now. But..

````
It should probably also get surfaced in values.yaml.
````
Can you elaborate?

**Comment by ggggut** [comment]
I also added the possibility to add annotations. This could be useful in a few cases.

**Comment by hairmare** [comment]
> ```
> It should probably also get surfaced in values.yaml.
> ```
> 
> Can you elaborate?

I didn't realise that `.postgres.host` is already defined in `values.yaml` :facepalm:

**Review by hairmare — APPROVED** [review]
LGTM

**Pull request merged**
