### PR TITLE
chore(argocd): update to v3.0.* | argocd version 2.0

### PR DESCRIPTION
**Pull request by eyenx**
# Description

Updates to latest argo-helm release using argocd version 2.0

Upgrade info: https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd#upgrading

```
3.0.0 and above

Helm apiVersion switched to v2. Requires Helm 3.0.0 or above to install. Read More on how to migrate your release from Helm 2 to Helm 3.
```

ArgoCD 2.0.0: Changelog with changes.

https://github.com/argoproj/argo-cd/releases/tag/v2.0.0

# Issues
n/a

# Checklist

* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run -a`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] If I updated a dependency tool, or app, this PR contains a short summary of the changes I'm pulling
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Review by vmaillot — APPROVED** [review]

**Review by hairmare — CHANGES_REQUESTED** [review]
Missing links to upstreams docs and a short summary of changes.

**Comment by eyenx** [comment]
> Missing links to upstreams docs and a short summary of changes.

done.

https://github.com/argoproj/argo-cd/releases/tag/v2.0.0

**Review by hairmare — APPROVED** [review]
(assuming the version will be updated as per when/what we merge before)

**Comment by tongpu** [comment]
> (assuming the version will be updated as per when/what we merge before)

I'm sorry.
@eyenx :cookie:

**Pull request merged**
