### PR TITLE
chore(helm-docs): Update to 1.5.0

### PR DESCRIPTION
**Pull request by eyenx**
* update to version 1.5.0
* update helm in ci to 3.4.2
* removal of version footer in README

### CODE REVIEW

**Comment by eyenx** [comment]
The versionfooter needs to be removed, so we do not need to version bump the charts everytime....

**Comment by eyenx** [comment]
@michaelimfeld 
https://github.com/adfinis-sygroup/helm-charts/pull/154/checks?check_run_id=1693490834#step:7:129
why this strange appVersion, which isn't even used anywhere?

@hairmare 
Somthing wrong on your configmap? 
https://github.com/adfinis-sygroup/helm-charts/pull/154/checks?check_run_id=1693490834#step:7:97

**Comment by hairmare** [comment]
> Somthing wrong on your configmap?

Looks like it needs a `trunc n | trimsuffix "-"` somewhere. I'm not sure why it previously failed though.

The helm-docs 1.5.0 introduce any interesting features?

**Comment by eyenx** [comment]
> The helm-docs 1.5.0 introduce any interesting features?

fixes some stuff:

```
e65dfab fix: fixes broken comment parsing on values files with dos line endings
ec63edc fix: fixes small formatting issue
```

**Comment by eyenx** [comment]
@michaelimfeld #156

**Comment by eyenx** [comment]
@hairmare #157

**Review by tongpu — APPROVED** [review]
LGTM

**Review by hairmare — APPROVED** [review]

**Pull request merged**
