### PR TITLE
chore(vault): update to 0.10.*

### PR DESCRIPTION
**Pull request by eyenx**
# Description

Updates vault to version `0.10.*`

Needs #207 first to be merged!

# Issues

n/a

# Checklist

* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run -a`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by hairmare** [comment]
What changes are to be expected by updating the vault chart to `0.10.*`?

**Comment by eyenx** [comment]
```
Features:
* Add support for [Vault CSI provider](https://github.com/hashicorp/vault-csi-provider) [GH-461](https://github.com/hashicorp/vault-helm/pull/461)
Improvements:
* `objectSelector` can now be set on the mutating admission webhook [GH-456](https://github.com/hashicorp/vault-helm/pull/456)
```

**Comment by hairmare** [comment]
Will this already contain the breaking changes from the 0.1.0 release of the vault csi driver?

**Comment by eyenx** [comment]
> Will this already contain the breaking changes from the 0.1.0 release of the vault csi driver?

Yes. But the csi driver is just newly supported inside the vault-helm chart, so it's not a breaking change for the chart itself, as it's rather a new feature already starting with version `0.1.0`

**Review by hairmare — APPROVED** [review]

**Pull request merged**
