### PR TITLE
feat(logging-apps): Bump filebeat to 7.17

### PR DESCRIPTION
**Pull request by isantospardo**
# Description

Update filebeat to 7.17.*

# Changes
- https://github.com/elastic/helm-charts/pull/1610 (https://github.com/elastic/helm-charts/commit/33a2829a181889a740e5afde46d1cba10124f89a)
- https://github.com/elastic/helm-charts/pull/1632
- https://github.com/elastic/helm-charts/pull/1602
- https://github.com/elastic/helm-charts/pull/1604

FFI: https://github.com/elastic/helm-charts/blob/main/CHANGELOG.md

Closes https://github.com/adfinis-sygroup/helm-charts/issues/664

# Issues

n/a

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Review by tongpu — APPROVED** [review]

**Review by hairmare — CHANGES_REQUESTED** [review]
The description seems to link to metricbeat and the warning about `helm upgrade --force` failing also seems to be metricbeat specific. can you clarify this in the description?

**Comment by isantospardo** [comment]
> The description seems to link to metricbeat and the warning about `helm upgrade --force` failing also seems to be metricbeat specific. can you clarify this in the description?

I have added it to the description of the issue, thanks for saying :)

**Comment by hairmare** [comment]
> I have added it to the description of the issue, thanks for saying :)

Thanks. I'm still a bit confused :confused: Do the `metricbeat` chart changes affect this PR? If not, please remove them from the description, or, explain why they do affect us when we update the `filebeat` chart.

**Comment by isantospardo** [comment]
> > I have added it to the description of the issue, thanks for saying :)
> 
> Thanks. I'm still a bit confused confused Do the `metricbeat` chart changes affect this PR? If not, please remove them from the description, or, explain why they do affect us when we update the `filebeat` chart.

Totally right, it only affects `metricbeat`, so nothing to do with `filebeat`, just removed the issue in the description

**Review by hairmare — APPROVED** [review]

**Pull request merged**
