### PR TITLE
feat(timed): add DATA_UPLOAD_MAX_NUMBER_FIELDS to env

### PR DESCRIPTION
**Pull request by trowik**
# Description

This value should be customizable as there are big projects that have a lot of tasks, tasks and project assignees. In such cases the amount of fields exceeds the default value of 1000, which makes saving any changes on that project impossible.

# Issues

- https://github.com/adfinis-sygroup/timed-backend/pull/805
# Checklist

* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run -a`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] If I updated a dependency tool, or app, this PR contains a short summary of the changes I'm pulling
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by trowik** [comment]
[timed-backend PR \#805](https://github.com/adfinis-sygroup/timed-backend/pull/805)

cc @winged

**Comment by hairmare** [comment]
you'll need to update containers version in this we merge it as well, right?

**Comment by trowik** [comment]
Yes, but have to do it on timed-test first.

**Review by hairmare — CHANGES_REQUESTED** [review]
- [x] update app version in values.yaml
https://github.com/adfinis-sygroup/helm-charts/blob/3f3c9081c424904f7b4ce559e267540423015548/charts/timed/values.yaml#L15

**Review by hairmare — APPROVED** [review]

**Pull request merged**
