### PR TITLE
Changing Version 3.5.0 of cephCsiRbd and cephCsiCephfs

### PR DESCRIPTION
**Pull request by RishiKumarRay**
# Description
Changing Version 3.5.0 of cephCsiRbd and cephCsiCephfs

# Issues 
- #532 
- #531 

# Checklist

* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] If I updated a dependency tool, or app, this PR contains a short summary of the changes I'm pulling
* [ ] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by hairmare** [comment]
Hey @RishiKumarRay Can you bump the version of the storage-apps chart in  helm-charts/charts/storage-apps/Chart.yaml and update  helm-charts/charts/storage-apps/README.md as well. Thanks!

**Comment by RishiKumarRay** [comment]
@hairmare Bump storage version , Sorry i didn't get this , can you please explain

**Comment by hairmare** [comment]
Since our charts have immutable versions, each change to the charts also need to update the version in the corresponding Chart.yaml. In this case the `version` line should be changed to `version: 0.6.0`

https://github.com/adfinis-sygroup/helm-charts/blob/e2c475824b476f2bc845ff2a420f79f001593e71/charts/storage-apps/Chart.yaml#L5

The README.md also contains references to this version as well as to the versions of the charts you are bumping. Thus the change should also be reflected in README.md.

**Comment by RishiKumarRay** [comment]
@hairmare Actually the version in chart.yml is already 0.6.0 should i change to 0.6.1

**Comment by hairmare** [comment]
ah, sorry, i meant `0.7.0` (given the upstream charts also bumps the minor version, we tend to try bump the minor as well)

**Comment by RishiKumarRay** [comment]
@hairmare Please review i have done the changes

**Review by hairmare — APPROVED** [review]

**Comment by hairmare** [comment]
I added an update to the version in README.md that was still missing and have approved you PR.

Thank you very much for your contribution!

**Comment by RishiKumarRay** [comment]
@hairmare  Thank you , Sorry I missed that

**Comment by hairmare** [comment]
@RishiKumarRay no worries, the README updating stuff is a bit convoluted. I also added a change to make the chart use the same patch level wildcard our others do.

**Pull request merged**
