### PR TITLE
feat(azure-apps): azurekvcsiprovider-1.0

### LINKED ISSUE #448: [azure-apps] version 1.0.1 of azureKvCsiProvider is available!
Hi!<br/></br>There is a new version available for azureKvCsiProvider!<br/><br/>current targetRevision set: `0.2.*`<br/>new version available: `1.0.0`<br/><br/>Please consider updating the  with a PR in this file [values.yaml](https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/azure-apps/values.yaml)<br/><br/>Thanks.

### PR DESCRIPTION
**Pull request by eyenx**
# Description

Updates secrets-store-cis-driver-provider-azure to version `1.0.*`

# Issues

closes #448

# Changes

**:exclamation: Read Upgrade notes :exclamation:**

[upgrading to v1.0.0 release](https://azure.github.io/secrets-store-csi-driver-provider-azure/upgrading/#upgrading-to-v100-release-for-the-driver-and-provider)

The new version uses API version v1 of SecretProviderClass

## Other Changes:

* add metrics for provider 
* adds windows server 2022
* update to driver v1.0.0 in helm charts
* make --driver-write-secrets flag no-op
* update to go 1.17 
* use ErrorS instead of Fatalf for structured logging 
* update build status badge to new pipeline 
* replace deprecated codecov uploader with GitHub action 
* add cherry_pick_pull script from kubernetes 
* bump ansi-regex from 5.0.0 to 5.0.1 in /website

# Checklist

* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run -a`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] If I updated a dependency tool, or app, this PR contains a short summary of the changes I'm pulling
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

### CODE REVIEW

**Comment by hairmare** [comment]
I was looking into this a bit ago and we need to make sure that our strategy here aligns with the move to secrets-store-cis-driver-provider-azure as an addon when on AKS (so it's supported/managed). The remaining use-case from the chart will be when we want to use Azure key/vault on non AKS clusters.

**Review by isantospardo — APPROVED** [review]
LGTM, probably we will need to create an internal issue to track all the different clients using this to upgrade them all at once.

**Comment by hairmare** [comment]
On AKS cluster we should probably not upgrade to this but rather activate the addon as documented: https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

The only reason to keep this app here is to use it on non AKS cluster or in other cases where the addon isn't available.

**Review by hairmare — APPROVED** [review]
lgtm on the condition that we don't just roll this out asap willy nilly but rather wait for the addon to be supported in "our" terraform upstream so we can remove this chart from the critical path and get on the regular upstream release chain with customers that early adopted azurekvcsiprovider for good reasons.

**Review by hairmare — CHANGES_REQUESTED** [review]
needs chart version bump to >0.3.0

**Review by hairmare — APPROVED** [review]

**Pull request merged**
