### PR TITLE
fix(infra-apps): bump nginx-ingress to 0.34.*

### PR DESCRIPTION
**Pull request by hairmare**
# Description

bump nginx-ingress chart to 0.34.*:

- Add namespace field in the namespace scoped resource templates (https://github.com/kubernetes/ingress-nginx/pull/7256)

# Issues

# Checklist

* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run -a`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] If I updated a dependency tool, or app, this PR contains a short summary of the changes I'm pulling
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Review by eyenx — COMMENTED** [review]
Why only a patchfix bump?

**Comment by hairmare** [comment]
> Why only a patchfix bump?

because the upstream change is a patch and not a feature

**Comment by eyenx** [comment]
Well the upstream version change is a major tho...

**Comment by hairmare** [comment]
> Well the upstream version change is from 0.33.x to 0.34.x tho... and not onlly a patchfix. Did they do it wrong?

They are still on 0.y.y for initial development which is described as follows in the SemVer spec:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Review by eyenx — APPROVED** [review]

**Pull request merged**
