### PR TITLE
feat(storage-apps): update nfs-client-provisioner to nfs-subdir-external-provisioner

### PR DESCRIPTION
**Pull request by hairmare**
# Description

Updates all of outdated nfs-client-provisioner stack to it's new "nfs-subdir-external-provisioner" upstream. 

BREAKING CHANGE rename of app in app and upstream repo + source change

# Issues

# Checklist

* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run -a`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] If I updated a dependency tool, or app, this PR contains a short summary of the changes I'm pulling
* [ ] CI is currently green and this is ready for review
* [ ] I am ready to test changes after they are applied and released
* [x] get feedback from @tongpu (doesn't think we use this anywhere)
* [x] get feedback from @eyenx

### CODE REVIEW

**Comment by hairmare** [comment]
This needs some pre ready for review feedback from @tongpu and @eyenx before i move it forward.

**Comment by eyenx** [comment]
AFAICR we do not use this anywhere.

**Comment by hairmare** [comment]
> AFAICR we do not use this anywhere.

Are there any plans to change this? The provisioner itself is certainly being used all over the place.

If we are going to stop using it the i'll remove it from `storage-apps`. If I can't convince y'all to stop using it then it stays and we shall talk about why it isn't argocd managed in those cases where it is in use.

**Comment by eyenx** [comment]
AFAIK it's only in use at Schindler on their Openshift. I can't recall any other customer using it.

--

Adfinis AG
Antonio Tauro, System Engineer, GPG KeyID: 0x0796132F0077A5F8
Güterstrasse 86 | CH-4053 Basel
Office +41 61 500 31 31 | Direct +41 61 500 31 37
www.adfinis.com



-----Original message-----

**Comment by eyenx** [comment]
I would suggest removing this from storage-apps.

**Comment by hairmare** [comment]
yupp, that's what i'm leaning towards anyway

**Pull request closed without merging**
