### PR TITLE
feat(tracing-apps): install opentelemetry-collector

### PR DESCRIPTION
**Pull request by hairmare**
# Description

Install the [OpenTelemetry Collector](https://opentelemetry.io/docs/collector/).

# Issues

# Checklist

* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] If I updated a dependency tool, or app, this PR contains a short summary of the changes I'm pulling
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by tongpu** [comment]
What's the plan for this? Are we already using this anywhere?

**Comment by hairmare** [comment]
> What's the plan for this? Are we already using this anywhere?

We are not using it anywhere yet but in a lot of cases it should be between the app and ie. a jaeger deployment. I have a couple of casees where i expect it too make sense soon (as in i told devs to use the otel-sdk for their language) and am expecting this to see some use then.

upstream describes it as follows:

> The OpenTelemetry Collector offers a vendor-agnostic implementation of how to receive, process and export telemetry data. It removes the need to run, operate, and maintain multiple agents/collectors. This works with improved scalability and supports open-source observability data formats (e.g. Jaeger, Prometheus, Fluent Bit, etc.) sending to one or more open-source or commercial back-ends. The local Collector agent is the default location to which instrumentation libraries export their telemetry data.

For the cases where i see us using the collector it helps with decoupling the actual implementation of the back-end from collection. This means the instrumentation library in the instrumented code can be more lightweight since it does not need to take care of things like backoffs and knowing about multiple backends.

**Review by isantospardo — APPROVED** [review]
From the point of view of the deployment, it looks good to me, but probably better to wait for @tongpu approval due to the ongoing discussions.

**Comment by hairmare** [comment]
@isantospardo rerequesting a review was not intended, i was fishing for a way to rerequest one from @tongpu

**Review by tongpu — APPROVED** [review]
> > What's the plan for this? Are we already using this anywhere?
> 
> We are not using it anywhere yet but in a lot of cases it should be between the app and ie. a jaeger deployment. I have a couple of casees where i expect it too make sense soon (as in i told devs to use the otel-sdk for their language) and am expecting this to see some use then.

Ok, this sound to me like the fluentd of Telemetry. :D

If this allows the developers to consume the only the OpenTelemetry library and the data can be sent to different tracing backends then you're good to go.

**Comment by tongpu** [comment]
> isantospardo rerequesting a review was not intended, i was fishing for a way to rerequest one from @tongpu

That probably didn't work, because my comment was not part of a review and because of that I didn't consume the review you requested yet.

**Comment by hairmare** [comment]
OpenTelemetry (and the collector) isn't just about tracing, it does full stack instrumentation including logs and metrics if you want to :)

**Comment by tongpu** [comment]
> OpenTelemetry (and the collector) isn't just about tracing, it does full stack instrumentation including logs and metrics if you want to :)

Just don't call it observability or I feel obliged to summon mipsytipsy onto you!

**Comment by hairmare** [comment]
:partying_face: o11y change merged :partying_face:

**Pull request merged**
