### PR TITLE
feat(infra-apps): allow adding annotations at the app level

### PR DESCRIPTION
**Pull request by hairmare**
# Description

Adds the possibility to add annotations on all the apps deployed via infra-apps.

If this works out to my liking i'll add it to all the other `*-apps` charts as well.

# Issues

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Review by eyenx — COMMENTED** [review]
can't this be accomplished w/ the common chart somehow?

**Comment by hairmare** [comment]
> can't this be accomplished w/ the common chart somehow?

the `common.labels.standard` template doesen't currently support this 

https://github.com/adfinis-sygroup/helm-charts/blob/9522f3cb28075dbd76dda6ff6ed9537064239ae8/charts/common/templates/_metadata_labels.tpl#L6-L14

i'm not sure how well adding suport would work given the template expects to have a root in it's `.` but i'll give it a try

**Review by vmaillot — APPROVED** [review]

**Comment by hairmare** [comment]
#649 contains an approach at doing this globally for all app-of-apps in a `*-apps` chart, we'll still need this to enable app specific annotations.

**Review by eyenx — APPROVED** [review]

**Comment by hairmare** [comment]
I'm gonna add the argoconfig bump as well before merging this

**Pull request merged**
