### PR TITLE
chore(updates): switch to latest tergetRevision

### PR DESCRIPTION
**Pull request by eyenx**
## infra

* ingress-nginx :arrow_up_small: `3.22.*`
* kube-prometheus-stack :arrow_up_small: `13.4.*`

## logging

* fluentd :arrow_up_small: `3.5.*`

## misc
* metallb :arrow_up_small: `2.2.*`

## security

* dex :arrow_up_small: `2.15.*`
* vault :arrow_up_small: `0.9.*`
* falco-exporter :arrow_up_small: `0.5.*`

## storage

* ceph-csi-rbd :arrow_up_small: `3.2.*`
* ceph-csi-cephfs :arrow_up_small: `3.2.*`

### CODE REVIEW

**Comment by eyenx** [comment]
I'll post the Changelog later in the day.

**Comment by eyenx** [comment]
## Ingress-nginx

Nothing breaking.

https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/CHANGELOG.md#3220

## kps

Nothing breaking.

https://github.com/prometheus-community/helm-charts/commit/164e84e852d5916627c6f02375b0f1c3c4c92290#diff-fc1a56fd7f1f12a544f40c63eea5899e19606cea9f3b5d3d3c976ab65b635a73

## fluentd

hostAliases configurable

https://github.com/bitnami/charts/commit/eaefbc16ad3cdd807a81d1ad8f67136a438963ab#diff-e397301da89344a34541e1e178b20643a6d2ab3ae735b506a66e755ac2932eb6

## metallb

hostALiases configurable

https://github.com/bitnami/charts/commit/70869aae80cfbb6400d26530c66197ce666c3829#diff-e3e2f6d3ae70b7ff73f037ec76a717bbdf318d6f54c92aeef72cf138b27e7b67

## dex

Latest available Chart version in deprecated archived `helm/charts` repository.

## vault

`0.9.0` is supported with k8s `v1.16` onwards. (several apiVersions changes to `v1` instead of `v1beta1`)

https://github.com/hashicorp/vault-helm/blob/master/CHANGELOG.md#090-january-5th-2021

## falco-exporter

minor changes
https://github.com/falcosecurity/charts/blob/master/falco-exporter/CHANGELOG.md#v050


## ceph-csi-rbd
Minor, Image Updates
## ceph-csi-cephfs
Minor, Image updates.

**Review by tongpu — APPROVED** [review]
LGTM

**Comment by hairmare** [comment]
Please split these into multiple PRs the next time. Combining changes like this makes it harder to pin down bugs should any occur (esp. regarding bumps to multiple apps in one chart).

**Pull request merged**
